language: php
php:
  - '7.0'

sudo: false

services:
  - apache
  - postgresql
  - redis-server

env:
  - TRAVIS_BUILD=1

addons:
  hosts:
    - gestas.org
  postgresql: "9.5"
  redis-server: "3.0.6"
  apt:
    packages:
      - apache2
      - libapache2-mod-php5

#before_install:

install: true

before_script:
  - make clean

script:
  - make tests

notifications:
  irc: "irc.freenode.org#gestas"
